version: "3.9"

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=${DOCKER_USER}
      - POSTGRES_PASSWORD=${DOCKER_PASSWORD}
      - POSTGRES_DB=docker
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: ${VOLUME_PREFIX}_postgres14
