# Generated by Django 5.2.4 on 2025-07-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupontype",
            name="description",
        ),
        migrations.AddField(
            model_name="coupon",
            name="max_dicount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Maximum discount value for the coupon",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="coupontype",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="coupontype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, help_text="Start date for the coupon validity", null=True
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(
                blank=True, help_text="End date for the coupon validity", null=True
            ),
        ),
    ]
