# Generated by Django 5.2.4 on 2025-07-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_coupontype_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupontype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
