# Generated by Django 5.2.4 on 2025-07-11 01:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_coupontype_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="user_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                help_text="List of user IDs who are aligible for this coupon",
                size=None,
            ),
        ),
    ]
