# Generated by Django 5.2.4 on 2025-07-11 02:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_coupon_user_ids"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="max_dicount_value",
            new_name="max_discount_value",
        ),
        migrations.AlterField(
            model_name="coupon",
            name="user_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                help_text="List of user IDs who are eligible for this coupon",
                size=None,
            ),
        ),
    ]
