# Generated by Django 5.2.4 on 2025-07-12 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_max_dicount_value_coupon_max_discount_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="user_ids",
        ),
        migrations.AlterField(
            model_name="coupontype",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="CouponAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        help_text="User Id to whom coupon is assigned", max_length=50
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_assignment",
                        to="core.coupon",
                    ),
                ),
            ],
            options={
                "unique_together": {("coupon", "user_id")},
            },
        ),
    ]
