# Generated by Django 5.2.4 on 2025-07-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_coupon_user_ids_alter_coupontype_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponassignment",
            name="user_id",
            field=models.IntegerField(
                help_text="User ID to whom the coupon is assigned"
            ),
        ),
    ]
